DROP TABLE CLUB
CASCADE CONSTRAINTS;

DROP SEQUENCE ROU_SEQ;
--CLUB

CREATE TABLE CLUB(
		CLUBSEQ NUMBER CONSTRAINT ROU_SEQ PRIMARY KEY 
		CLUBTITLE VARCHAR2(200),
		CLUBTEXT VARCHAR2(4000),
		CLUBDATE DATE,
		CLUBIMAGE VARCHAR2(100),
		CLUBDEL NUMBER,
		ID VARCHAR2(20)
  		CONSTRAINT FK_ROU FOREIGN KEY (ID) 
        REFERENCES FK_MEM(ID) 
)

ALTER SEQUENCE ROU_SEQ
INCREMENT BY 1
START BY 1000

 