DROP TABLE APPLYBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE APP_SEQ;

--APPLYBBS

CREATE TABLE APPLYBBS(
		APPLYBBSSEQ NUMBER,
		APPLYBBSTITLE VARCHAR2(200),
		APPLYBBSCONTENT VARCHAR2(4000),
		APPLYBBSDATE DATE,
		APPLYBBSDEL NUMEBER,
		
		LIKESEQ NUMBER,  --좋아요
		EMAIL VARCHAR2(50),
		
  		CONSTRAINT FK_APP FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_APP2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)


CREATE SEQUENCE APP_SEQ
START WITH 10000
INCREMENT BY 1

SELECT * FROM APPLYBBS

 