DROP TABLE CHALLENGECHAT
CASCADE CONSTRAINTS;

DROP SEQUENCE CHAT_SEQ;

--CHALLENGECHAT

CREATE TABLE CHALLENGECHAT(
		CHATSEQ NUMBER CONSTRAINT CHAT_PRI PRIMARY KEY, 
		TOTALCOUNT NUMBER,  --전체 인원수
		REMAINCOUNT NUMBER,  --접속 인원수
		CHATCONTENT VARCHAR2(2000),   --대화내용
		CHATDATE DATE,
		
		CHALLENGESEQ NUMBER,
		EMAIL VARCHAR2(50) NOT NULL,
		
		
  		CONSTRAINT FK_CHAT FOREIGN KEY (EMAIL) 
	    REFERENCES MEMBER(EMAIL),
	    CONSTRAINT FK_CHAT2 FOREIGN KEY (CHALLENGESEQ) 
	    REFERENCES CHALLENGE(CHALLENGESEQ)
)


CREATE SEQUENCE CHAT_SEQ
START WITH 100
INCREMENT BY 1

SELECT * FROM CHALLENGECHAT
