DROP TABLE CHALLENGE
CASCADE CONSTRAINTS;

DROP SEQUENCE CHAL_SEQ;

--CHALLENGE

CREATE TABLE CHALLENGE(
		CHALLENGESEQ NUMBER, 
		CATEGORY NUMBER,     --카테고리
		CHALLENGETITLE VARCHAR2 (200),
		CHALLENGETEXT VARCHAR2 (4000),
		CHALLENGESTART DATE,  --시작일
		CHALLENGEEND DATE,    --종료일
		CHALLENGEPERIOD VARCHAR2, --기간
		IDENTIFYFREQUENCY NUMBER, --인증 빈도
		IDENTIFYTIME DATE, --인증 시간
		CHALLENGEPHOTO VARCHAR2(100),
		RATINGAVG NUMBER, --별점 평균
		CHALLENGESTOP NUMBER, --정지
		CHALLENGEDEL NUMBER, --삭제
		HEADERNUM NUMBER,   --개설자,  관리자:0 유저:3
		POINTCOUNT NUMBER,  --기준 포인트(얼마 걸껀지)
		
		EMAIL VARCHAR2(50), 
		CONSTRAINT CHAL_PK PRIMARY KEY(CHALLENGESEQ, IDENTIFYFREQUENCY),
		CONSTRAINT FK_CHAL FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
) 

--1	건강
--2	역량
--3	정서
--4	자산
--5	생활
--6	취미

--관리자 0, 멤버 3

CREATE SEQUENCE CHAL_SEQ
START WITH 1000
INCREMENT BY 1

SELECT * FROM CHALLENGE;
 

--IDENTIFYFREQUENCY 인증 빈도
--1 월 일 매일 인증하기
--2 월 금 매일 인증하기
--3 토 일 매일 인증하기
--4 주6일 인증하기
--5 주5일 인증하기
--4 주4일 인증하기
--3 주3일 인증하기
--2 주 2일 인증하기
--1 주 1일 인증하기

--IDENTIFYFREQUENCY TABLE만들기
--COLUMNS : IDENTIFYFREQUENCY, 요일7개


CREATE TABLE IDENTIFYFREQUENCY(
	IDENTIFYFREQUENCY NUMBER,
	SUNDAY NUMBER, --1
	MONDAY NUMBER, --2
	TUESDAY NUMBER, --3
	WEDNESDAY NUMBER, --4
	THURSDAY NUMBER, --5
	FRIDAY NUMBER, --6
	SATERDAY NUMBER --7
	CONSTRAINT FK_IDEN FOREIGN KEY (IDENTIFYFREQUENCY) 
	REFERENCES CHALLENGE(IDENTIFYFREQUENCY)
)