DROP TABLE CHALLENGEWISH
CASCADE CONSTRAINTS;

DROP SEQUENCE WISH_SEQ;

--CHALLENGEWISH

CREATE TABLE CHALLENGEWISH(
   	WISHSEQ NUMBER CONSTRAINT PK_WISH PRIMARY KEY,
   	WISH NUMBER,  --찜하기  1
   	CHALLENGESEQ NUMBER,
   	EMAIL VARCHAR2(50),
	CONSTRAINT FK_WISH FOREIGN KEY (EMAIL) 
    REFERENCES MEMBER(EMAIL),
    CONSTRAINT FK_WISH2 FOREIGN KEY (CHALLENGESEQ) 
    REFERENCES CHALLENGE(CHALLENGESEQ)
)

 
CREATE SEQUENCE WISH_SEQ
START WITH 5000
INCREMENT BY 1

SELECT * FROM CHALLENGEMEMBER

SELECT F.FOLLOWSEQ, F.FOLLOW, F.FOLLOWEMAIL, F.FOLLOWINGEMAIL
		FROM FOLLOW F, CHALLENGEMEMBER C
		WHERE F.FOLLOWEMAIL = C.EMAIL
			AND C.CHALLENGESEQ = #{challengeseq}
			AND F.FOLLOWEMAIL = #{email}


--follow 사람 좋아요
CREATE TABLE FOLLOW(
   	FOLLOWSEQ NUMBER CONSTRAINT PK_FOLL PRIMARY KEY,
   	FOLLOW NUMBER,  --1이면 좋아요
   	FOLLOWEMAIL VARCHAR2(50),		--LIKE누른 사람
   	FOLLOWINGEMAIL VARCHAR2(50),	--LIKE 당한 사람
	CONSTRAINT FK_FOLL FOREIGN KEY (FOLLOWEMAIL) 
    REFERENCES MEMBER(EMAIL),
    CONSTRAINT FK_FOLL2 FOREIGN KEY (FOLLOWINGEMAIL) 
    REFERENCES MEMBER(EMAIL)
)

CREATE SEQUENCE FOLL_SEQ
START WITH 5000
INCREMENT BY 1

SELECT * FROM CHALLENGEMEMBER
	
SELECT * FROM MEMBER
SELECT * FROM FOLLOW
DELETE FROM FOLLOW
WHERE FOLLOW = 1

SELECT * FROM FOLLOW

		SELECT F.FOLLOWSEQ, F.FOLLOW, F.FOLLOWEMAIL, F.FOLLOWINGEMAIL
		FROM FOLLOW F, CHALLENGMEMBER C
		WHERE F.FOLLOWEMAIL = C.EMAIL
			AND C.CHALLENGESEQ = #{challengeseq}
			AND F.FOLLOWEMAIL = #{email}
