DROP TABLE CHALLENGEMEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE CHALMEM_SEQ;

--CHALLENGEMEMBER

CREATE TABLE CHALLENGEMEMBER(
		CHALLENGMEMSEQ NUMBER CONSTRAINT CHALLMEM_PRI PRIMARY KEY,
		IDENTIFY NUMBER,  --인증 횟수
		SUCCESS NUMBER -- 성공실패 성공시1 85퍼이상 2 실패3
		CHALLENGESEQ NUMBER,
		EMAIL VARCHAR2(50) NOT NULL,
  		CONSTRAINT FK_CHALMEM FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL), 
        CONSTRAINT FK_CHALMEM2 FOREIGN KEY (CHALLENGESEQ) 
        REFERENCES CHALLENGE(CHALLENGESEQ) 
)

ALTER TABLE CHALLENGEMEMBER ADD SUCCESS NUMBER;

CREATE SEQUENCE CHALMEM_SEQ
START WITH 100
INCREMENT BY 1

SELECT * FROM CHALLENGEMEMBER

UPDATE MEMBER
SET POINT = 10000
WHERE EMAIL = 'final.5623@gmail.com'

UPDATE MEMBER
		SET POINT = POINT-5
		WHERE EMAIL = 'final.5623@gmail.com'
		

SELECT CM.CHALLENGMEMSEQ, M.EMAIL, M.NICKNAME, M.MEMBERPHOTONAME, M.POINT, CM.CHALLENGESEQ, CM.IDENTIFY
FROM MEMBER M, CHALLENGEMEMBER CM
WHERE M.EMAIL = CM.EMAIL
	AND CM.CHALLENGESEQ = 1100
ORDER BY CM.CHALLENGMEMSEQ DESC

SELECT * FROM CHALLENGE WHERE CHALLENGESEQ = 1100

SELECT * FROM MEMBER
UPDATE CHALLENGE
		SET CHALLENGEMEMBER = CHALLENGEMEMBER+1
		WHERE CHALLENGESEQ = 1100	

SELECT CHALLENGMEMSEQ, IDENTIFY, SUCCESS, CHALLENGESEQ, EMAIL
FROM CHALLENGEMEMBER