DROP TABLE CHALLENGE
CASCADE CONSTRAINTS;

DROP SEQUENCE CHAL_SEQ;

--CHALLENGE

CREATE TABLE CHALLENGE(
		CHALLENGESEQ NUMBER CONSTRAINT MEM_PRI PRIMARY KEY, 
		CATEGORY NUMBER,     --카테고리
		CHALLENGETITLE VARCHAR2 (200),
		CHALLENGETEXT VARCHAR2 (4000),
		CHALLENGESTART DATE,  --시작일
		CHALLENGEEND DATE,    --종료일
		IDENTIFYFREQUENCY NUMBER, --인증 빈도
		IDENTIFYDAY VARCHAR2(50),
		IDENTIFYTIME DATE, --인증 시간
		IDENTIFYCOUNT NUMBER, --인증 횟수
		CHALLENGEPHOTO VARCHAR2(100),
		RATINGAVG NUMBER, --별점 평균
		CHALLENGESTOP NUMBER, --정지
		CHALLENGEDEL NUMBER, --삭제
		HEADERNUM NUMBER,   --개설자,  관리자:0 유저:3
		POINTCOUNT NUMBER,  --기준 포인트(얼마 걸껀지)
		
		EMAIL VARCHAR2(50), 
		
		CONSTRAINT FK_CHAL FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
) 

--1	건강
--2	역량
--3	정서
--4	자산
--5	생활
--6	취미

--관리자 0, 멤버 3

CREATE SEQUENCE CHAL_SEQ
START WITH 1000
INCREMENT BY 1

SELECT * FROM CHALLENGE;
 