DROP TABLE CLUBBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE CBBS_SEQ;
--CLUBBBS

CREATE TABLE CLUBBBS(
		BBSSEQ NUMBER CONSTRAINT BBS_PRI PRIMARY KEY, 
		BBSTITLE VARCHAR2(200),
		BBSCONTENT VARCHAR2(4000),
		BBSDATE DATE,
		BBSREF NUMBER,
		BBSSTEP NUMBER,
		BBSDEPTH NUMBER,
		BBSDEL NUMBER,
		READCOUNT NUMBER,
		ID VARCHAR2(20),
		CLUBSEQ NUMBER,
  		CONSTRAINT FK_BBS FOREIGN KEY (ID) 
        REFERENCES MEMBER(ID),
        CONSTRAINT FK_CSEQ FOREIGN KEY (CLUBSEQ) 
        REFERENCES CLUB(CLUBSEQ) 
)

ALTER SEQUENCE CBBS_SEQ
INCREMENT BY 1
START BY 1000

 