DROP TABLE COMMENT
CASCADE CONSTRAINTS;

DROP SEQUENCE COM_SEQ;
--COMMENT

CREATE TABLE COMMENT(
		COMSEQ NUMBER CONSTRAINT COM_PRI PRIMARY KEY, 
		COMCONTENT VARCHAR2(500),
		COMDATE DATE,
		COMRATING NUMBER,
		COMREF NUMBER,
		COMSTEP NUMBER,
		COMDEPTH NUMBER,
		COMDEL NUMBER,
		ID VARCHAR2(20),
		BBSSEQ NUMBER,
  		CONSTRAINT FK_COM FOREIGN KEY (ID) 
        REFERENCES MEMBER(ID),
        CONSTRAINT FK_COMBBS FOREIGN KEY (BBSSEQ) 
        REFERENCES CLUBBBS(BBSSEQ)
        
)

ALTER SEQUENCE COM_SEQ
INCREMENT BY 1
START BY 5000
