DROP TABLE MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE MEM_SEQ;
--MEMBER

CREATE TABLE MEMBER(
		ID VARCHAR2(20) CONSTRAINT MEM_PRI PRIMARY KEY, 
		PWD VARCHAR2 (20),
		MBTI VARCHAR2(10),
		GENDER NUMBER,
		EMAIL VARCHAR2(50),
		PHONE VARCHAR2(50),
		AUTH NUMBER,
		NICKNAME VARCHAR2(20),
		AREA VARCHAR2(100),
		IMAGE VARCHAR2(50),
		AGE NUMBER,
		INTRODUCE VARCHAR2(4000),
		HOBBY1 VARCHAR2(20),
		HOBBY2 VARCHAR2(20),
		HOBBY3 VARCHAR2(20),
		APPLYCOUNT NUMBER,
		DEL NUMBER,
		RELATED NUMBER,
		CONSTRAINT MEM_PRI PRIMARY KEY(ID, NICKNAME, AREA),
  		CONSTRAINT FK_MEMMBTI FOREIGN KEY (MBTI) 
        REFERENCES MBTI(MBTI)
)

ALTER SEQUENCE MEM_SEQ
INCREMENT BY 1
START BY 1

 