DROP TABLE MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE MEM_SEQ;
--MEMBER

CREATE TABLE MEMBER(
		MEMBERSEQ NUMBER,
		EMAIL VARCHAR2(50) CONSTRAINT MEM_PRI PRIMARY KEY, 
		NICKNAME VARCHAR2(50),
		MEMBERPHOTO VARCHAR2(200),
		NAVERLOGIN VARCHAR2(50),
		KAKAOLOGIN VARCHAR2(50),
		GOOGLELOGIN VARCHAR2(50),
		AUTH NUMBER,
		MEMBERDEL NUMBER,
		POINT NUMBER
)
--관리자 1, 멤버 3

ALTER TABLE MEMBER

ALTER TABLE MEMBER MODIFY(EMAIL VARCHAR2(50))
ALTER TABLE MEMBER ADD(POINT NUMBER)

SELECT * FROM MEMBER

DELETE FROM MEMBER
WHERE NICKNAME = '라이블리네이버'

COMMIT

CREATE SEQUENCE MEM_SEQ
START WITH 1
INCREMENT BY 1

INSERT INTO MEMBER (MEMBERSEQ, EMAIL, NICKNAME, MEMBERPHOTO, NAVERLOGIN, KAKAOLOGIN, GOOGLELOGIN, AUTH, MEMBERDEL, POINT)
VALUES(MEM_SEQ.NEXTVAL, 'admin', '매니저', '0', null, null, null, 1, 0, 0);