DROP TABLE MESSAGE
CASCADE CONSTRAINTS;

DROP SEQUENCE MES_SEQ;
--MESSAGE

CREATE TABLE MESSAGE(
		MESSAGESEQ NUMBER CONSTRAINT MES_PRI PRIMARY KEY, 
		ID VARCHAR2(20),
		PARTNERID VARCHAR2(20),
		MESSAGECONTENT VARCHAR2(4000),
		WDATE DATE,
  		CONSTRAINT FK_MES FOREIGN KEY (ID) 
        REFERENCES MEMBER(ID),
        CONSTRAINT FK_PMES FOREIGN KEY (PARTNERID) 
        REFERENCES MEMBER(ID)
)

ALTER SEQUENCE MES_SEQ
INCREMENT BY 1
START BY 500

 