DROP TABLE MYLIKE
CASCADE CONSTRAINTS;

DROP SEQUENCE LIKE_SEQ;

SELECT * FROM MYLIKE
-- 제안하기(마이페이지) 게시판 좋아요

CREATE TABLE MYLIKE(
		LIKESEQ NUMBER CONSTRAINT MYLIKE_PRI PRIMARY KEY,
		APPLYBBSSEQ NUMBER,
		EMAIL VARCHAR2(50),
					
  		CONSTRAINT FK_LIKE FOREIGN KEY (APPLYBBSSEQ) 
        REFERENCES APPLYBBS(APPLYBBSSEQ),
        CONSTRAINT FK_LIKE2 FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_LIKE3 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)


CREATE SEQUENCE LIKE_SEQ
START WITH 5000
INCREMENT BY 1
