DROP TABLE SCHEDULE
CASCADE CONSTRAINTS;

DROP SEQUENCE SCH_SEQ;

--SCHEDULE

CREATE TABLE SCHEDULE(
		SCHEDULESEQ NUMBER CONSTRAINT SCH_PRI PRIMARY KEY, 
		
		CHALLENGESEQ NUMBER,
		EMAIL VARCHAR2(50),
		
  		CONSTRAINT FK_SCH FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL),
        CONSTRAINT FK_SCH2 FOREIGN KEY (CHALLENGESEQ) 
        REFERENCES CHALLENGE(CHALLENGESEQ)
)

ALTER TABLE SCHEDULE MODIFY(EMAIL VARCHAR2(50))

CREATE SEQUENCE SCH_SEQ
START WITH 10000
INCREMENT BY 1

 