DROP TABLE SUGGESTBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SUG_SEQ;

--APPLYBBS

CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT SUG_PRI PRIMARY KEY,
		SUGGESTBBSCATEGORY NUMBER,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)

ALTER TABLE SUGGESTBBS ADD WDATE DATE

/*
CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT APP_PRI PRIMARY KEY,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDATE DATE,
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)
*/

CREATE SEQUENCE SUG_SEQ
START WITH 10000
INCREMENT BY 1

SELECT * FROM SUGGESTBBS

SELECT * FROM SUGGESTCOMMENT

SELECT SUGGESTBBSSEQ, SUGGESTBBSCATEGORY, SUGGESTBBSTITLE, LIKESEQ, ROWNUM as SI FROM SUGGESTBBS

SELECT SUGCOMSEQ,SUGCOMCONTENT, TO_CHAR(SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGGESTBBSSEQ, SUGCOMDATE, SUGCOMDEL
FROM SUGGESTCOMMENT 
WHERE SUGGESTBBSSEQ = #{suggestbbsseq}

SELECT SUGCOMSEQ FROM SUGGESTCOMMENT ORDER BY SUGCOMSEQ DESC, SUGCOMCONTENT, TO_CHAR(SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGCOMDATE, SUGCOMDEL, SUGGESTBBSSEQ, 
(SELECT COUNT(*) FROM SUGGESTCOMMENT) TOTALCNT
FROM SUGGESTCOMMENT 
WHERE SUGGESTBBSSEQ = #{suggestbbsseq}


SELECT SUGCOMSEQ, SUGCOMCONTENT, TO_CHAR(SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGCOMDATE, SUGCOMDEL, SUGGESTBBSSEQ, 
(SELECT COUNT(*) FROM SUGGESTCOMMENT) TOTALCNT
FROM SUGGESTCOMMENT 
WHERE SUGGESTBBSSEQ = #{suggestbbsseq}


SELECT SCT.SUGCOMSEQ, SCT.SUGCOMCONTENT, TO_CHAR(SCT.SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGCOMDATE, SUGCOMDEL, SUGGESTBBSSEQ 
(SELECT ROW_NUMBER() OVER(ORDER BY SUGCOMSEQ DESC) AS CI
FROM SUGGESTCOMMENT SCT 
(SELECT COUNT(*) FROM SUGGESTCOMMENT WHERE SUGCOMDEL = 0) AS TOTALCNT
WHERE SUGGESTBBSSEQ = #{suggestbbsseq}
AND SUGCOMDEL = 0


SELECT SUGCOMSEQ, SUGCOMCONTENT, TO_CHAR(SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGCOMDATE, SUGCOMDEL, SUGGESTBBSSEQ
FROM SUGGESTCOMMENT,
(SELECT * FROM SUGGESTCOMMEN, ROW_NUMBER OVER(ORDER BY SUGCOMDATE DESC)) AS CI,
(SELECT COUNT(*) FROM SUGGESTCOMMENT WHERE SUGCOMDEL = 0) AS TOTALCNT
FROM SUGGESTCOMMENT A
WHERE SUGGESTBBSSEQ = '10021'
AND SUGCOMDEL = 0


SELECT AC.* FROM
(SELECT ROW_NUMBER() OVER(ORDER BY SUGCOMDATE) AS RNUM,
SUGCOMSEQ, SUGCOMCONTENT, TO_CHAR(SUGCOMDATE,'YYYY-MM-DD HH24:MI:SS') AS SUGCOMDATE, SUGCOMDEL, SUGGESTBBSSEQ FROM SUGGESTCOMMENT
ORDER BY RNUM DESC)AS CI,
(SELECT COUNT(*) FROM SUGGESTCOMMENT WHERE SUGCOMDEL = 0) AS TOTALCNT
FROM SUGGESTCOMMENT AC
WHERE SUGGESTBBSSEQ = '10021'

SELECT * FROM SUGGESTCOMMENT WHERE SUGCOMDEL = 0

(SELECT SBS.*, ROW_NUMBER() OVER(ORDER BY SBS.SUGGESTBBSSEQ DESC) as SI, 전체에서 SEQ를 역순으로 가져와

(SELECT COUNT(*) FROM SUGGESTBBS
WHERE  SUGGESTBBSDEL = 0
AND SUGGESTBBSCATEGORY = #{category}
AND SUGGESTBBSTITLE LIKE '%'||#{search}||'%') as TOTALCNT 토탈 뽑아 와

FROM SUGGESTBBS SBS

LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT

ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ

LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = #{email}) ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE  SBS.SUGGESTBBSDEL = 0
AND SBS.SUGGESTBBSCATEGORY = #{category}
AND SBS.SUGGESTBBSTITLE LIKE '%'||#{search}||'%') SV

WHERE SV.SI > #{startPage} AND #{endPage} > SV.SI




SELECT SM.*
FROM (SELECT ROWNUM as SI,SV.* FROM
   (SELECT SBS.*, 
   CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
   CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK,
   (SELECT COUNT(*) FROM SUGGESTBBS
   WHERE  SUGGESTBBSDEL = 0
   ) as TOTALCNT
   FROM SUGGESTBBS SBS
   LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT
   ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ
   LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = '') ML
   ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
   WHERE  SBS.SUGGESTBBSDEL = 0
         ORDER BY SBS.SUGGESTBBSSEQ DESC
         ) SV
)SM
WHERE SM.SI > 0 AND 6 > SM.SI

delete from suggestbbs

delete from suggestcomment

delete from mylike

select * from mylike

UPDATE SUGGESTBBS
SET WDATE = TO_DATE('2021-06-16 11:05:00', 'YYYY-MM-DD HH:MI:SS')
WHERE
SUGGESTBBSCATEGORY = 1