DROP TABLE SUGGESTBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SUG_SEQ;

--APPLYBBS

CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT SUG_PRI PRIMARY KEY,
		SUGGESTBBSCATEGORY NUMBER,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)

/*
CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT APP_PRI PRIMARY KEY,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDATE DATE,
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)
*/

CREATE SEQUENCE SUG_SEQ
START WITH 10000
INCREMENT BY 1

SELECT * FROM SUGGESTBBS

SELECT SUGGESTBBSSEQ, SUGGESTBBSCATEGORY, SUGGESTBBSTITLE, LIKESEQ, ROWNUM as SI FROM SUGGESTBBS



SELECT SV.*,
(SELECT COUNT(*)
FROM SUGGESTBBS) AS TOTALCNT
FROM
(SELECT SUGGESTBBSSEQ, SUGGESTBBSCATEGORY, SUGGESTBBSTITLE, LIKESEQ, ROWNUM as SI 
FROM SUGGESTBBS) SV
WHERE SV.SI > #{startPage} AND #{endPage} > SV.SI


SELECT SBS.*,	-- suggestbbs 전체 리스트를 가져옴
CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK

FROM SUGGESTBBS SBS	-- bbs 게시판으로부터

LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT -- 라이크 테이블에 seq로 좋아요 숫자 카운트
ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ	-- 조건 두 테이블의 sseq 값 동일?

LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = 'ywoo0309@gmail.com') ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE SBS.SUGGESTBBSDEL = 0

---------------------------------페이징 쿼리 완료
SELECT SV.* FROM
(SELECT SBS.*, ROWNUM as SI, 
CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK
FROM SUGGESTBBS SBS
LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT
ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ
LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = 'ywoo0309@gmail.com') ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE SBS.SUGGESTBBSDEL = 0 ) SV
WHERE SV.SI >= '1' AND '3' >= SV.SI


SELECT SV.* FROM
(SELECT SBS.*, ROW_NUMBER() OVER (ORDER BY SBS.SUGGESTBBSSEQ DESC) as SI, 
CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK
FROM SUGGESTBBS SBS
LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT
ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ
LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = 'ywoo0309@gmail.com') ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE SBS.SUGGESTBBSDEL = 0 ) SV
WHERE SV.SI >= '1' AND '3' >= SV.SI


------------------------------검색까지 넣은거 완료
SELECT SV.* FROM
(SELECT SBS.*, ROWNUM as SI, 
CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK
FROM SUGGESTBBS SBS
LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT
ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ
LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = 'ywoo0309@gmail.com') ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE 1=1
	AND SBS.SUGGESTBBSDEL = 0
		<if test="category !=null and category !=''">
			AND SBS.SUGGESTBBSCATEGORY = ${SUGGESTBBSCATEGORY}
		</if>
		<if test="search !=null and search != ''">
			AND SBS.SUGGESTBBSTITLE LIKE '%'||#{search}||'%'
		</if>
		ORDER BY SBS.SUGGESTBBSSEQ ASC) SV
WHERE SV.SI >= #{startPage} AND #{endPage} >= SV.SI


SELECT * FROM SUGGESTBBS

SELECT NVL(COUNT(*), 0)
FROM SUGGESTBBS
WHERE 1=1 
AND SUGGESTBBSDEL = 0 
AND SUGGESTBBSCATEGORY = ${SUGGESTBBSCATEGORY}
AND SUGGESTBBSTITLE LIKE '%'||#{search}||'%'







SELECT SV.* FROM
(SELECT SBS.*, ROWNUM as SI, 
CASE WHEN CNT.LIKECNT IS NULL THEN 0 ELSE CNT.LIKECNT END AS LIKECNT,
CASE WHEN ML.SUGGESTBBSSEQ IS NULL THEN 0 ELSE 1 END AS LIKECHECK
FROM SUGGESTBBS SBS
LEFT JOIN (SELECT SUGGESTBBSSEQ,COUNT(*) AS LIKECNT FROM MYLIKE GROUP BY SUGGESTBBSSEQ) CNT
ON SBS.SUGGESTBBSSEQ = CNT.SUGGESTBBSSEQ
LEFT JOIN (SELECT SUGGESTBBSSEQ FROM MYLIKE WHERE EMAIL = 'ywoo0309@gmail.com') ML
ON SBS.SUGGESTBBSSEQ = ML.SUGGESTBBSSEQ
WHERE 1=1
	AND SBS.SUGGESTBBSDEL = 0
			AND SBS.SUGGESTBBSCATEGORY = ${SUGGESTBBSCATEGORY}
			AND SBS.SUGGESTBBSTITLE LIKE '%'||#{search}||'%'
		ORDER BY SBS.SUGGESTBBSSEQ ASC) SV
WHERE SV.SI >= #{startPage} AND #{endPage} >= SV.SI
