DROP TABLE SUGGESTBBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SUG_SEQ;

--APPLYBBS

CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT SUG_PRI PRIMARY KEY,
		SUGGESTBBSCATEGORY NUMBER,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)

/*
CREATE TABLE SUGGESTBBS(
		SUGGESTBBSSEQ NUMBER CONSTRAINT APP_PRI PRIMARY KEY,
		SUGGESTBBSTITLE VARCHAR2(200),
		SUGGESTBBSCONTENT VARCHAR2(4000),
		SUGGESTBBSDATE DATE,
		SUGGESTBBSDEL NUMBER,
		LIKESEQ NUMBER,
		EMAIL VARCHAR2(50),
  		CONSTRAINT FK_SUG FOREIGN KEY (LIKESEQ) 
        REFERENCES MYLIKE(LIKESEQ),
        CONSTRAINT FK_SUG2 FOREIGN KEY (EMAIL) 
        REFERENCES MEMBER(EMAIL)
)
*/

CREATE SEQUENCE SUG_SEQ
START WITH 10000
INCREMENT BY 1

SELECT * FROM SUGGESTBBS

 